openapi: "3.0.0"
info:
  title: API Products
  version: "0.0"
paths:
  /api/products/:
    get:
      summary: Get products
      tags:
        - Products
      parameters:
        - name: limit
          in: query
          required: false
          description: Max number of retrieved products. Default value 10.
          schema:
            type: number
        - name: page
          in: query
          required: false
          description: Page number
          schema:
            type: number
        - name: category
          in: query
          required: false
          description: Sort products by category
          schema:
            type: string
      responses:
        "200":
          description: Products retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "500":
          description: An internal error has occurred

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: Autogenerated MongoDB ID
        title:
          type: string
          description: Product title
        owner:
          type: string
          description: Email from product owner
        description:
          type: string
          description: Product description
        price:
          type: number
          description: Product price in USD currency
        image:
          type: string
          description: URL address to retrieve product image
        code:
          type: number
          description: Unique identifier code
        stock:
          type: number
          description: Available stock number
        available:
          type: boolean
          description: Product availability
      example:
        owner: Admin
        _id: 63e67167f52471bc74414ab0
        title: ThinkPad
        description: 50% off
        price: 950
        image: image
        code: 1000
        stock: 996
        category: electronics
        available: true
